### ISSUE TITLE
stringenc.sty not found

### ISSUE THREAD

**Issue by mjh127** [MiKTeX/miktex-packaging#148]
After the latest update of 2019-12-01, lualatex runs into a problem with the package oberdiek. The file 'stringenc.sty' cannot be found.

**Comment by zach-oster** [comment]
I was just struggling with this same issue. It seems to be caused by ongoing work to split the oberdiek package into smaller, more modular packages: stringenc.sty has been moved out of the oberdiek package into its own package named "stringenc", kvoptions.sty is now in its own package named "kvoptions", and so on.

See #145 for a similar issue with kvoptions.sty (which also affected me earlier). For more background info, see [the related issue on the oberdiek package's GitHub](https://github.com/ho-tex/oberdiek/issues/77).

It looks like the MikTeX package servers have *just* been updated to include the new stringenc and kvoptions packages, as of about 5 minutes ago. In the MikTeX console, update your package database (Tasks -> Update package database). After you do this, you should see a new package "stringenc" in the package list. Install this package, and then the problem should be solved.

**Comment by edocevoli** [comment]
Thank you. The package `stringenc` is now installable.
