### ISSUE TITLE
Packaging problem of 'luacolor'?

### ISSUE THREAD

**Issue by fpantigny** [MiKTeX/miktex-packaging#396]
I have just updated MikTeX and `luacolor` does not work any longer.

```
\documentclass{article}
\usepackage{luacolor}
\begin{document}
Test.
\end{document}
```

When I compile (with LuaLaTeX, of course), I have the following message:

```
[\directlua]:1: module 'luacolor' not found:
	no field package.preload['luacolor']
	[kpse lua searcher] file not found: 'luacolor'
```

I suspect an error in the packaging of the package `luacolor`...

**Comment by RosenlindDylan** [comment]
Hello,
I am new to contributing but I figured I'd give it a shot. I didn't find any recent changes to the packages that might cause this issue, but the CTAN distribution of the luacolor package itself was updated yesterday 8/19/23 so that may need to be updated. However CONTRIBUTING.md states, "Please do not request a packages update unless the MiKTeX version lacks behind the CTAN more then a month." So I am not sure if it is to be updated soon. As @edocevoli is the sole contributor they'll likely be able to answer this better.
Hope this helped somewhat! Good luck

**Comment by fpantigny** [comment]
I have just downloaded the last version of `luacolor` on CTAN. I have run `tex luacolor.dtx`, such extracting the files `luacolor.sty` and `luacolor.lua`. When I put those files in the repertory of my document, I have no problem using `luacolor`.

I suspect that both files should be in the repertory `\tex\latex\luacolor` of the `texmf` tree. When I look at a TeXLive distribution on Ubuntu, I find both files in `\tex\latex\luacolor`. Now, when I look in my MikTeX installation, I only find the file `luacolor.sty` (and my error message precisely says that the file `luacolor.lua` could not been found). That's why I think that the file `luacolor.lua` is lacking.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.

**Comment by fpantigny** [comment]
Thanks.
