### ISSUE TITLE
glyphtounicode-ntx.tex missing

### ISSUE THREAD

**Issue by JDan04** [MiKTeX/miktex-packaging#78]
Hello

I tried building a file using Texmaker and MiKTeX and this error popped up. 

![image](https://user-images.githubusercontent.com/46163580/50448787-697fcf80-0923-11e9-8afd-2f2c722a7034.png)

I've checked the path and found the file (glyphtounicode-ntx.tex) there. I've also tried redownloading the file (pdfx) and replacing it, but that didn't help either. I was told to write here. 

What should I do now?

Thanks for help

**Comment by u-fischer** [comment]
A minimal example for the problem is

~~~~
\documentclass{article}
\usepackage{pdfx}
\begin{document}
blb
\end{document}
~~~~

This gives the error 

~~~~
! I can't find file `glyphtounicode-ntx.tex'.
l.2354  \input glyphtounicode-ntx.tex
~~~~

The missing file is part of pdfx on ctan. În texlive it is in c:/texlive/2018/texmf-dist/tex/latex/pdfx/glyphtounicode-ntx.tex.

**Comment by edocevoli** [comment]
Thank you, I have updated the pdfx package.
Please check for updates tomorrow.
