### ISSUE TITLE
Poppler package warning

### ISSUE THREAD

**Issue by rend3r** [MiKTeX/miktex-packaging#8]
Today (October 26, 2017)  I got this warning after update:

> initexmf: warning: The link target F:\LaTEX\texmfs\install\miktex/bin\miktex-pdfsig.exe does not exist.

As far as I know miktex-poppler-bin should provide miktex-pdfsig.exe but currently the file is not present. I am not sure how it's crucial but decide report the possible issue.

**Comment by edocevoli** [comment]
`miktex-pdfsig.exe` is currently not working and has been excluded. I will eliminate the warning.

**Comment by Dylan-newusr** [comment]
Dear fellows,

I have recently adopted the idea of using more convenient methods for large document manipulations, such as thesis, articles and etc.  I have recently installed Latex ( MikTex 2.9) and tried my first steps with it. Unfortunately, immediately I have stumbled on several issues:

**_1)_** When I try to compile/create a simple pdf document, there is a nasty error, repeatedly showing, no matter what methods I use to prevent it:
 
**_"Sorry, but "MiKTeX Configuration Utility" did not succeed.

The log file hopefully contains the information to get MiKTeX going again:

  C:/Users/DDI/AppData/Local/MiKTeX/2.9/miktex/log/initexmf.log

You may want to visit the MiKTeX project page (http://miktex.org), if you
need help."_**

Initially, I tried to handle it by going to _**MiKTeX Settings (admin) > General tab > Update Formats**_ and update everything which was proposed. Then, I went to  **_package manager (admin), use repositories -> synchronize_** + rebooting. So far, so good, but the same message appears again and again :/ Finally, I opened the update **_section(admin)_**, from where there is another error message: 
**_2)_** **_"Windows API error 87: The parameter is incorrect"._**

Honestly, I am completely unaware of what else should I do, in order to manage completely with these nasty errors! Therefore, I would be very grateful of any kind of advices for successful solution and dealing with these issues! 

Thanks in advance,
Me, the noob in Latex :)

**Comment by edocevoli** [comment]
This has been fixed.
