### ISSUE TITLE
pgf.sty not found

### ISSUE THREAD

**Issue by mehrt** [MiKTeX/miktex-packaging#80]
Updated MiKTeX packages to latest versions this morning, after that "pfg.sty" wasn't to be found anywhere.
A manual install of the contents of http://mirrors.ctan.org/install/graphics/pgf/base/pgf.tds.zip into the tex root folder fixed this.

**Comment by moewew** [comment]
Indeed after the update from this morning
```
\documentclass{article}
\usepackage{tikz}

\begin{document}
Lorem

\begin{tikzpicture}
\draw (0,0) --(1,2);
\end{tikzpicture}
\end{document}
```
will just produce the error
```
! LaTeX Error: File `tikz.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)
```
and https://miktex.org/Package/Browse/pgf only contains the source archive and no runtime files.

I assume that is due to the unusual distribution on CTAN noted in the [INSTALL_NOTES](http://mirrors.ctan.org/graphics/pgf/base/INSTALL_NOTES). TeX live has https://tug.org/pipermail/tex-live-commits/2019-January/008331.html.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.

**Comment by moewew** [comment]
Thank you very much. The issue indeed seems to be fixed by this morning's update.

**Comment by dlopatin-v** [comment]
2024 and I see the issue using the latest portable distributive
